services:
  mysqldb:
    image: mysql:8.0
    hostname: mysqldb
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: samir
      MYSQL_USER: samir
      MYSQL_PASSWORD: samir
    ports:
      - "3309:3306"
    volumes:
      - samir-mysql-new:/var/lib/mysql

  config-server:
    image: hakimamarullah/starline-scc:v1.0.1
    restart: on-failure
    environment:
      JAVA_OPTS: -DUSERNAME=${USERNAME} -DPERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN} -Djdk.tls.client.protocols=TLSv1.2
      JAVA_ARGS: --spring.cloud.config.server.git.skipSslValidation=true

    ports:
      - "9999:9999"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: backend
    depends_on:
      - mysqldb
      - config-server
    ports:
      - "8080:8080"
    environment:
      JAVA_ARGS: --spring.profiles.active=dev
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3309/samir?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta
      SPRING_DATASOURCE_USERNAME: samir
      SPRING_DATASOURCE_PASSWORD: samir
      SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:9999?fail-fast=true&max-attempts=10
      MYSQL_PORT: 3309

volumes:
  samir-mysql-new: