services:
  mysql-samir:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - samir-mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: samir
      MYSQL_USER: samir
      MYSQL_PASSWORD: samir
    ports:
      - "3309:3306"
    volumes:
      - samir-mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - samir-mysql-network
    depends_on:
      - mysql-samir
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-samir:3309/samir?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: samir
      SPRING_DATASOURCE_PASSWORD: samir

volumes:
  samir-mysql:

networks:
  samir-mysql-network:
    driver: bridge
