services:
  mysqldb:
    image: mysql:8.0
    hostname: mysqldb
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: samir
      MYSQL_USER: samir
      MYSQL_PASSWORD: samir
    ports:
      - "3309:3306"
    volumes:
      - samir-mysql-new:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: backend
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3309/samir?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta
      SPRING_DATASOURCE_USERNAME: samir
      SPRING_DATASOURCE_PASSWORD: samir
      MYSQL_PORT: 3309

volumes:
  samir-mysql-new: